name: Run Server Script (Windows)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install sgfmill flask flask_socketio openai

      - name: Download KataGo
        run: |
          # Replace with the CORRECT Windows download link!
          curl -LO https://github.com/lightvector/KataGo/releases/download/v1.14.0/katago-v1.14.0-windows-x64.zip
          Expand-Archive -Path katago-v1.14.0-windows-x64.zip -DestinationPath .\.github\workflows\Katago\kataexe
          Move-Item -Path ".\.github\workflows\Katago\kataexe\katago-v1.14.0-windows-x64\katago.exe" -Destination ".\.github\workflows\Katago\kataexe\katago.exe"

      - name: Verify KataGo permissions
        run: ls -l .github\workflows\Katago\kataexe\katago.exe

      - name: Run server script
        run: python .github\workflows\server.py
