name: Run Server Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install sgfmill flask flask_socketio openai

      - name: Download KataGo
        run: |
          # Replace with the ABSOLUTELY CORRECT download link!
          wget [THE CORRECT LINK YOU OBTAINED FROM THE RELEASES PAGE]
          unzip [THE CORRECT ZIP FILE NAME]
          mkdir -p .github/workflows/Katago/kataexe
          mv [THE CORRECT EXTRACTED BINARY FILE NAME] .github/workflows/Katago/kataexe/katago.exe
          chmod +x .github/workflows/Katago/kataexe/katago.exe

      - name: Grant execute permissions to KataGo Folder.
        run: chmod +x .github/workflows/Katago/kataexe

      - name: Verify KataGo permissions
        run: ls -l .github/workflows/Katago/kataexe/katago.exe

      - name: Run server script
        run: python .github/workflows/server.py
